[package]
name = "rust_crash"
version = "0.1.0"
authors = ["Sebastian Fernandez <sefernan@microsoft.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.40"